import "./globals.css";
import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import { Provider } from "@/components/provider";

const body = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-sans",
});

const heading = Oswald({
  subsets: ["latin"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${body.variable} ${heading.variable} scroll-pt-32`}
    >
      <body className={`antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
